import dayjs from 'dayjs';

export const registerFieldList = [
  {
    name: 'Add_RelatedAccount',
    class: 'register__form__field--recommend',
    type: 'text',
    rules: { 'register-required': false, 'register-max': 15 },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_Account',
    class: 'register__form__field--account',
    type: 'text',
    rules: {
      'register-required': false,
      'register-min': 3,
      'register-max': 15,
      'register-regex': '^[a-zA-Z]{1}[a-zA-Z0-9]*$',
    },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_Password',
    class: 'register__form__field--password',
    type: 'password',
    rules: {
      'register-required': false,
      'register-min': 6,
      'register-max': 30,
      'register-regex': '^[a-zA-Z0-9]*$',
    },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_PasswordCheck',
    class: 'register__form__field--password',
    type: 'password',
    rules: {
      'register-required': false,
      'register-min': 6,
      'register-max': 30,
      'register-regex': '^[a-zA-Z0-9]*$',
      'register-confirmed': 'Add_Password',
    },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_Mobile',
    class: 'register__form__field--callphone',
    type: 'tel',
    rules: {
      'register-required': false,
      'register-min': 5,
      'register-max': 20,
      'register-regex': '^[0-9]+[0-9]*$',
    },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_Email',
    class: 'register__form__field--name',
    type: 'text',
    rules: {
      'register-required': false,
      'register-max': 50,
      'register-regex': '\\w+([-+.]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*',
    },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_Line',
    class: 'register__form__field--name',
    type: 'text',
    rules: { 'register-required': false },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_Skype',
    class: 'register__form__field--name',
    type: 'text',
    rules: { 'register-required': false, 'register-max': 12 },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_QQ',
    class: 'register__form__field--name',
    type: 'text',
    rules: { 'register-required': false },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_FirstName',
    class: 'register__form__field--name',
    type: 'text',
    rules: {
      'register-required': false,
      'register-regex': '^[A-Za-z]+$|^[\u4e00-\u9fa5\uF900-\uFA2D]+$|^[\u0e00-\u0e5b]+$',
      'register-max': 70,
    },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_LastName',
    class: 'register__form__field--name',
    type: 'text',
    rules: {
      'register-required': false,
      'register-regex': '^[A-Za-z]+$|^[\u4e00-\u9fa5\uF900-\uFA2D]+$|^[\u0e00-\u0e5b]+$',
      'register-max': 70,
    },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_RealName',
    class: 'register__form__field--name',
    type: 'text',
    rules: {
      'register-required': false,
      'register-regex': '^[A-Za-z ]+$|^[\u4e00-\u9fa5\uF900-\uFA2D]+$|^[\u0e00-\u0e5b]+$',
      'register-max': 70,
    },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_NickName',
    class: 'register__form__field--name',
    type: 'text',
    rules: { 'register-required': false, 'register-max': 30 },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_Birthday',
    class: 'register__form__field--name',
    type: 'date',
    rules: {
      'register-required': false,
      'register-regex': '^[1-9][0-9]{3}-[0-1][0-9]-[0-3][0-9]$',
      'register-birthday': {
        min: '1900-01-01',
        max: dayjs()
          .subtract(18, 'year')
          .format('YYYY-MM-DD'),
      },
    },
    min: '1900-01-01',
    max: dayjs()
      .subtract(18, 'year')
      .format('YYYY-MM-DD'),
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: dayjs()
      .subtract(18, 'year')
      .format('YYYY-MM-DD'),
  },
  {
    name: 'Add_BankId1',
    class: 'register__form__field--name',
    type: 'select',
    rules: { 'register-required': false },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_BankBranchName1',
    class: 'register__form__field--name',
    type: 'text',
    rules: { 'register-required': false, 'register-max': 70 },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_BankAccount1',
    class: 'register__form__field--account',
    type: 'text',
    rules: { 'register-required': false, 'register-max': 30 },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_BankId2',
    class: 'register__form__field--name',
    type: 'select',
    rules: { 'register-required': false },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_BankBranchName2',
    class: 'register__form__field--name',
    type: 'text',
    rules: { 'register-required': false, 'register-max': 70 },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_BankAccount2',
    class: 'register__form__field--account',
    type: 'text',
    rules: { 'register-required': false, 'register-max': 30 },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_BankId3',
    class: 'register__form__field--name',
    type: 'select',
    rules: { 'register-required': false },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_BankBranchName3',
    class: 'register__form__field--name',
    type: 'text',
    rules: { 'register-required': false, 'register-max': 70 },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_BankAccount3',
    class: 'register__form__field--account',
    type: 'text',
    rules: { 'register-required': false, 'register-max': 30 },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_Withdrawals_Password',
    class: 'register__form__field--password',
    type: 'password',
    rules: {
      'register-required': false,
      'register-min': 6,
      'register-max': 30,
      'register-regex': '^[a-zA-Z0-9]*$',
    },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'Add_Withdrawals_CheckPassword',
    class: 'register__form__field--password',
    type: 'password',
    rules: {
      'register-required': false,
      'register-min': 6,
      'register-max': 30,
      'register-regex': '^[a-zA-Z0-9]*$',
      'register-confirmed': 'Add_Withdrawals_Password',
    },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
  {
    name: 'CaptchaValue',
    class: 'register__form__field--code',
    type: 'tel',
    rules: {
      'register-required': false,
      'register-min': 4,
      'register-max': 4,
      'register-regex': '^[0-9]*$',
    },
    isRequired: false,
    isShow: false,
    isOnly: false,
    isModifiable: true,
    value: '',
  },
];
